# Generated by Django 2.0 on 2018-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20180108_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='values',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
