# Generated by Django 2.0 on 2018-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20180206_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprofile',
            name='values',
            field=models.TextField(default=''),
        ),
    ]
