# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
