# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_quote_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name_plural': 'text'},
        ),
    ]
