# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_auto_20171211_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
