# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0005_auto_20171211_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='text',
            new_name='name',
        ),
    ]
