# Generated by Django 2.0.1 on 2018-01-08 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_auto_20171216_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
