# Generated by Django 2.0.1 on 2018-01-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0009_quote_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprofile',
            name='favorites',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteprofile',
            name='seen',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoteprofile',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
