# Generated by Django 2.0.1 on 2018-01-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0010_auto_20180111_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
