# Generated by Django 2.0.1 on 2018-01-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0011_quoteprofile_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprofile',
            name='favoritesCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteprofile',
            name='seenCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quoteprofile',
            name='favorites',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quoteprofile',
            name='seen',
            field=models.TextField(default=''),
        ),
    ]
