# Generated by Django 2.0.1 on 2018-01-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0012_auto_20180111_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
