# Generated by Django 2.0.1 on 2018-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0013_auto_20180111_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='favorites',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='quoteprofile',
            name='seen',
            field=models.TextField(default='', null=True),
        ),
    ]
