# Generated by Django 2.0.1 on 2018-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0014_auto_20180111_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='favorites',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quoteprofile',
            name='seen',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quoteprofile',
            name='updated',
            field=models.DateField(),
        ),
    ]
