# Generated by Django 2.0.1 on 2018-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0015_auto_20180111_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='updated',
            field=models.DateField(blank=True),
        ),
    ]
