# Generated by Django 2.0.1 on 2018-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0017_auto_20180111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
