# Generated by Django 2.0.1 on 2018-01-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0018_auto_20180111_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprofile',
            name='currentDay',
            field=models.IntegerField(default=0),
        ),
    ]
