# Generated by Django 2.0.1 on 2018-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0019_quoteprofile_currentday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='currentDay',
            field=models.IntegerField(default=1),
        ),
    ]
